default:
  image: node:latest
  before_script:
    - cd lambda
    - yarn install --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
  cache:
    paths:
      - $CI_PROJECT_DIR/.yarn

variables:
  SENTRY_RELEASE_VERSION: $CI_PIPELINE_IID

.default_rules: &default_rules
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - when: never

.deploy_rules: &deploy_rules
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_DEPLOY_FREEZE != null'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never

stages:
  - test
  - build
  - deploy
  - sync

lint code:
  <<: *default_rules
  stage: test
  script:
    - yarn lint

lint translations:
  <<: *default_rules
  stage: test
  script:
    - utility-scripts/check-for-new-translations.sh

lint model:
  <<: *default_rules
  image: nathanfriend/java-node-git:latest
  stage: test
  script:
    - utility-scripts/check-for-model-changes.sh

jest:
  <<: *default_rules
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - lambda/test-report.xml
    reports:
      junit: lambda/test-report.xml

build:
  <<: *default_rules
  stage: build
  needs: []
  script:
    - yarn build
  artifacts:
    paths:
      - lambda/build/

deploy:
  <<: *deploy_rules
  stage: deploy
  script:
    - utility-scripts/deploy.sh
  environment:
    name: development

upload source maps:
  <<: *deploy_rules
  stage: deploy
  script:
    - yarn sentry-cli releases files $SENTRY_RELEASE_VERSION upload-sourcemaps build --url-prefix="/var/task/build/"
    - yarn sentry-cli releases files $SENTRY_RELEASE_VERSION upload src --url-prefix="/var/task/build/"

upload assets:
  <<: *deploy_rules
  stage: deploy
  script:
    - utility-scripts/upload-assets-to-s3.js

sync:
  stage: sync
  script:
    - utility-scripts/merge-old-database-into-new-database.js
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - when: never
