default:
  image: node:latest
  before_script:
    - cd lambda
    - yarn install --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
  cache:
    paths:
      - lambda/node_modules/
      - $CI_PROJECT_DIR/.yarn

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  SENTRY_RELEASE_VERSION: $CI_PIPELINE_IID

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - yarn lint

jest:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - lambda/test-report.xml
    reports:
      junit: lambda/test-report.xml

build:
  stage: build
  needs: []
  script:
    - yarn build
  artifacts:
    paths:
      - lambda/build/

deploy:
  stage: deploy
  script:
    - yarn install --prod --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
    - cd $CI_PROJECT_DIR
    - apt-get update
    - apt-get --yes install moreutils gettext
    - envsubst < ask-resources.json | sponge ask-resources.json
    - cat ask-resources.json
    - yarn global add ask-cli --cache-folder $CI_PROJECT_DIR/.yarn
    - ask deploy
    - cd lambda
    - yarn install --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
  environment:
    name: development
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

upload source maps:
  stage: deploy
  script:
    - yarn sentry-cli releases files $SENTRY_RELEASE_VERSION upload-sourcemaps build --url-prefix="/"
    - yarn sentry-cli releases files $SENTRY_RELEASE_VERSION upload src --url-prefix="/"
