default:
  image: node:latest
  before_script:
    - cd lambda
    - yarn install --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
  cache:
    paths:
      - lambda/node_modules/
      - $CI_PROJECT_DIR/.yarn

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - yarn lint

jest:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - lambda/test-report.xml
    reports:
      junit: lambda/test-report.xml

build:
  stage: build
  needs: []
  script:
    - yarn build
  artifacts:
    paths:
      - lambda/build/

deploy:
  stage: deploy
  needs:
    - build
  script:
    - yarn install --prod --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
    - cd $CI_PROJECT_DIR
    - yarn global add ask-cli --cache-folder $CI_PROJECT_DIR/.yarn
    - ask deploy
    - cat .ask/ask-states.json
    - cd lambda
    - yarn install --frozen-lockfile --cache-folder $CI_PROJECT_DIR/.yarn
  environment:
    name: development
